export * from './aPI.service';
import { APIService } from './aPI.service';
export * from './detalleReceta.service';
import { DetalleRecetaService } from './detalleReceta.service';
export * from './efectoAdverso.service';
import { EfectoAdversoService } from './efectoAdverso.service';
export * from './historialMedico.service';
import { HistorialMedicoService } from './historialMedico.service';
export * from './login.service';
import { LoginService } from './login.service';
export * from './medicamento.service';
import { MedicamentoService } from './medicamento.service';
export * from './paciente.service';
import { PacienteService } from './paciente.service';
export * from './receta.service';
import { RecetaService } from './receta.service';
export * from './rol.service';
import { RolService } from './rol.service';
export * from './userRol.service';
import { UserRolService } from './userRol.service';
export * from './usuarios.service';
import { UsuariosService } from './usuarios.service';
export const APIS = [APIService, DetalleRecetaService, EfectoAdversoService, HistorialMedicoService, LoginService, MedicamentoService, PacienteService, RecetaService, RolService, UserRolService, UsuariosService];
