/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Paciente } from './paciente';
import { Medicamento } from './medicamento';


export interface EfectoAdverso { 
    idEfecto?: number;
    idPaciente?: number | null;
    idMedicamento?: number | null;
    fechaReporte?: string;
    descripcion?: string | null;
    gravedad?: string | null;
    lote?: string | null;
    laboratorio?: string | null;
    registroSanitario?: string | null;
    fechaVencimiento?: string;
    dosis?: string | null;
    fechaInicioEfecto?: string | null;
    fechaFinEfecto?: string | null;
    viaAdministracion?: string | null;
    medidasTomadas?: string | null;
    suspension?: string | null;
    fechaSuspension?: string | null;
    ajusteDosis?: string | null;
    dosisActual?: string | null;
    idMedicamentoNavigation?: Medicamento;
    idPacienteNavigation?: Paciente;
}

