/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Paciente } from './paciente';


export interface HistorialMedico { 
    idHistorial?: number;
    idPaciente?: number | null;
    idMedico?: number | null;
    fecha?: string;
    diagnostico?: string | null;
    tratamiento?: string | null;
    idPacienteNavigation?: Paciente;
}

