/**
 * API.Srv-inventory
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UsuarioCreateDto { 
    username?: string | null;
    email?: string | null;
    estado?: string | null;
    nombre?: string | null;
    apellido?: string | null;
    id?: number;
    password?: string | null;
}

