/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Recetum } from './recetum';
import { Medicamento } from './medicamento';


export interface DetalleRecetum { 
    idDetalle?: number;
    idReceta?: number | null;
    idMedicamento?: number | null;
    dosis?: string | null;
    frecuencia?: string | null;
    duracion?: string | null;
    idMedicamentoNavigation?: Medicamento;
    idRecetaNavigation?: Recetum;
}

