/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EfectoAdverso } from './efectoAdverso';
import { DetalleRecetum } from './detalleRecetum';


export interface Medicamento { 
    idMedicamento?: number;
    nombre?: string | null;
    composicion?: string | null;
    indicaciones?: string | null;
    contraindicaciones?: string | null;
    fechaRegistro?: string;
    detalleReceta?: Array<DetalleRecetum> | null;
    efectoAdversos?: Array<EfectoAdverso> | null;
}

