/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EfectoAdverso } from './efectoAdverso';
import { HistorialMedico } from './historialMedico';
import { Recetum } from './recetum';


export interface Paciente { 
    idPaciente?: number;
    nombre?: string | null;
    fechaNacimiento?: string;
    genero?: string | null;
    contacto?: string | null;
    fechaRegistro?: string;
    efectoAdversos?: Array<EfectoAdverso> | null;
    historialMedicos?: Array<HistorialMedico> | null;
    receta?: Array<Recetum> | null;
}

