/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Paciente } from './paciente';
import { DetalleRecetum } from './detalleRecetum';


export interface Recetum { 
    idReceta?: number;
    idPaciente?: number | null;
    idMedico?: number | null;
    fechaEmision?: string;
    observaciones?: string | null;
    detalleReceta?: Array<DetalleRecetum> | null;
    idPacienteNavigation?: Paciente;
}

